version: 2
jobs:
  build:
    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-bundle-{{ checksum "Gemfile.lock" }}
            - rails-bundle-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec
          command: |
            bundle exec rspec
